Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost"
  copyright: 
  #analytics: UA-YOURCODE
  staticroot: "http://localhost/static"

Development:
  <<: *defaults

Testing:
  <<: *defaults
  port: 3001
  approot: "http://test.leaguefamous.com"
  staticroot: "http://test.leaguefamous.com/static"

Staging:
  <<: *defaults

Production:
  approot: "http://www.leaguefamous.com"
  #staticroot: "http://static.leaguefamous.com/"
  staticroot: "http://www.leaguefamous.com/static"
  <<: *defaults
