Default: &defaults
  database: leaguesay.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: leaguesay_test.sqlite3
  <<: *defaults

Staging:
  database: leaguesay_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: leaguesay_production.sqlite3
  poolsize: 100
  <<: *defaults
